version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "3"
        NODE_VERSION: "lts/*"
    volumes:
      - ..:/workspace:cached
      - vscode-extension-data:/vscode/.vscode-server/extensions
    command: sleep infinity
    network_mode: service:db
  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./create-db-user.sql:/docker-entrypoint-initdb.d/create-db-user.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
  pgadmin:
    image: dpage/pgadmin4:8
    ports:
      - "9090:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
volumes:
  postgres-data:
  vscode-extension-data:
